version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request
  artifacts:
    - name: saver
      attestations:
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
        - name: unit-test
          type: junit
        - name: unit-test-branch-coverage
          type: generic
