version: 1

trail:
  attestations:
    - name: tf-plan-beta
      type: generic
    - name: tf-plan-prod
      type: generic
  artifacts:
    - name: state-beta
    - name: state-prod
    - name: saver
      attestations:
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
        - name: branch-coverage
          type: generic
