version: 2

jobs:

  build-test-push:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Build, test, push image to dockerhub (tagged)
          command: |
            ./scripts/merkely_declare_pipeline.sh
            ./build.sh
            ./up.sh
            ./wait.sh
            ./test.sh
            ./scripts/images_push.sh
            ./scripts/merkely_log_artifact.sh
            ./scripts/merkely_log_evidence.sh


  deploy-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to beta with helm
          command: ./.circleci/deploy_to_namespace.sh beta


  merkely-log-deployment-to-beta:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log deployment to beta in Merkely
          command: ./scripts/merkely_log_deployment.sh beta


  merkely-approve-deployment:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Approve deployment in Merkely
          command: |
            ./scripts/merkely_approve_deployment.sh


  deploy-to-prod:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to prod with helm
          command: ./.circleci/deploy_to_namespace.sh prod


  merkely-log-deployment-to-prod:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log deployment to prod in Merkely
          command: ./scripts/merkely_log_deployment.sh prod


  push-latest:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Push image to dockerhub (latest)
          command: ./scripts/images_push.sh latest


workflows:

  version: 2

  build-test-push-deploy:
    jobs:

      - build-test-push:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]

      - deploy-to-beta:
          context: cyberdojo-context
          requires: [ build-test-push ]

      - merkely-log-deployment-to-beta:
          context: cyberdojo-context
          requires: [ deploy-to-beta ]

      - approve-to-prod:
          type: approval
          requires: [ deploy-to-beta ]

      - merkely-approve-deployment:
          context: cyberdojo-context
          requires: [ approve-to-prod ]

      - deploy-to-prod:
          context: cyberdojo-context
          requires: [ merkely-approve-deployment ]

      - merkely-log-deployment-to-prod:
          context: cyberdojo-context
          requires: [ deploy-to-prod ]

      - push-latest:
          context: cyberdojo-context
          requires: [ deploy-to-prod ]
