version: 2

jobs:

  build-test-push:
    machine:
      image: ubuntu-2004:202008-01
      #docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build, test, push image to dockerhub (tagged)
          command: |
            ./build.sh
            ./up.sh
            ./wait.sh
            ./test.sh
            ./push.sh


  deploy-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      #- setup_remote_docker:
      #    docker_layer_caching: true
      - run:
          name: Authenticate with gcloud, deploy to beta with helm
          command: ./.circleci/deploy_to_namespace.sh beta


  deploy-to-prod:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      #- setup_remote_docker:
      #    docker_layer_caching: true
      - run:
          name: Authenticate with gcloud, deploy to prod with helm
          command: ./.circleci/deploy_to_namespace.sh prod


  push-latest:
    machine:
      image: ubuntu-2004:202008-01
      #docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Push image to dockerhub (latest)
          command: ./push.sh latest


workflows:

  version: 2

  build-test-push-deploy:
    jobs:

      - build-test-push:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]

      - deploy-to-beta:
          context: cyberdojo-context
          requires: [ build-test-push ]

      - approve-to-prod:
          type: approval
          requires: [ deploy-to-beta ]

      - deploy-to-prod:
          context: cyberdojo-context
          requires: [ approve-to-prod ]

      - push-latest:
          context: cyberdojo-context
          requires: [ deploy-to-prod ]
