
fullnameOverride: "saver"

updateStrategy: "Recreate"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: saver-tmp-dir
    emptyDir: {}
  - name: saver-data
    persistentVolumeClaim:
      claimName: saver-data

containers:
  - name: saver
    volumeMounts:
      - name: saver-tmp-dir
        mountPath: /tmp
        readOnly: false
      - name: saver-data
        mountPath: /cyber-dojo
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_SAVER_PORT: "4537"
      CYBER_DOJO_CUSTOM_START_POINTS_PORT: "4526"
      CYBER_DOJO_EXERCISES_START_POINTS_PORT: "4525"
      CYBER_DOJO_LANGUAGES_START_POINTS_PORT: "4524"
    livenessProbe:
      path: /alive
    readinessProbe:
      path: /ready
