require_relative 'base58'
require_relative 'client_error'
require 'json'

# Checks for arguments syntactic correctness

class WellFormedArgs

  def initialize(s)
    @args = JSON.parse(s)
  rescue
    raise ClientError.new('json:malformed')
  end

  # - - - - - - - - - - - - - - - -

  def manifest
    arg = args['manifest']
    unless arg.is_a?(Hash)
      malformed('manifest', '!Hash')
    end
    missing_key?(arg) do |key|
      malformed("manifest[#{key.inspect}]", 'missing')
    end
    unknown_key?(arg) do |key|
      malformed("manifest[#{key.inspect}]", 'unknown')
    end
    arg.keys.each do |key|
      arg_name = "manifest[#{key.inspect}]"
      value = arg[key]
      case key
      when 'created'
        well_formed_time(arg_name, value)
      when 'id','group'
        well_formed_id(arg_name, value)
      when 'display_name', 'exercise'
        well_formed_string(arg_name, value)
      when 'image_name', 'runner_choice'
        well_formed_string(arg_name, value)
      when 'visible_files'
        well_formed_files(arg_name, value)
      when 'filename_extension'
        well_formed_filename_extension(arg_name, value)
      when 'highlight_filenames','progress_regexs','hidden_filenames'
        well_formed_array_of_strings(arg_name, value)
      when 'tab_size'
        well_formed_tab_size(arg_name, value)
      when 'max_seconds'
        well_formed_max_seconds(arg_name, value)
      end
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def id
    well_formed_id('id', args['id'])
  end

  def indexes
    well_formed_indexes('indexes', args['indexes'])
  end

  def index
    well_formed_index('index', args['index'])
  end

  def files
    well_formed_files('files', args['files'])
  end

  def now
    well_formed_time('now', args['now'])
  end

  def duration
    well_formed_duration('duration', args['duration'])
  end

  def stdout
    well_formed_string('stdout', args['stdout'])
  end

  def stderr
    well_formed_string('stderr', args['stderr'])
  end

  def status
    well_formed_status('status', args['status'])
  end

  def colour
    well_formed_colour('colour', args['colour'])
  end

  private # = = = = = = = = = = = =

  attr_reader :args

  def missing_key?(manifest)
    REQUIRED_KEYS.each do |key|
      unless manifest.keys.include?(key)
        yield key
      end
    end
  end

  REQUIRED_KEYS = %w(
    display_name
    image_name
    runner_choice
    created
    visible_files
  )

  # - - - - - - - - - - - - - - - -

  def unknown_key?(manifest)
    manifest.keys.each do |key|
      unless KNOWN_KEYS.include?(key)
        yield key
      end
    end
  end

  KNOWN_KEYS = REQUIRED_KEYS + %w(
    id
    group
    exercise
    filename_extension
    highlight_filenames
    hidden_filenames
    progress_regexs
    tab_size
    max_seconds
  )

  # - - - - - - - - - - - - - - - -

  def well_formed_filename_extension(arg_name, arg)
    if arg.is_a?(String)
      arg = [ arg ]
    end
    well_formed_array_of_strings(arg_name, arg)
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_tab_size(arg_name, arg)
    unless arg.is_a?(Integer)
      malformed(arg_name, '!Integer')
    end
    unless (1..8).include?(arg)
      malformed(arg_name, "!(1..8)")
    end
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_max_seconds(arg_name, arg)
    unless arg.is_a?(Integer)
      malformed(arg_name, '!Integer')
    end
    unless (1..20).include?(arg)
      malformed(arg_name, "!(1..20)")
    end
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_duration(arg_name, arg)
    unless arg.is_a?(Float)
      malformed(arg_name, '!Float')
    end
    unless arg >= 0.0
      malformed(arg_name, '!(>= 0.0)')
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_id(arg_name, arg)
    unless Base58.string?(arg)
      malformed(arg_name, '!Base58')
    end
    unless arg.size == 6
      malformed(arg_name, "size==#{arg.size} -> !6")
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_files(arg_name, arg)
    unless arg.is_a?(Hash)
      malformed(arg_name, '!Hash')
    end
    arg.each { |filename,content|
      # arg is generated by JSON.parse()
      # and json hash keys can only be stringd
      unless content.is_a?(String)
        malformed(arg_name, "[#{filename.inspect}] -> !String")
      end
    }
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_indexes(arg_name, arg)
    unless arg.is_a?(Array)
      malformed(arg_name, '!Array')
    end
    unless arg.length == 64
      malformed(arg_name, "size==#{arg.size} -> !64")
    end
    unless arg.sort == (0..63).to_a
      malformed(arg_name, '!(0..63)')
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_index(arg_name, arg)
    unless arg.is_a?(Integer)
      malformed(arg_name, '!Integer')
    end
    unless arg >= -1
      malformed(arg_name, 'argument out of range')
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_status(arg_name, arg)
    unless arg.is_a?(Integer)
      malformed(arg_name, '!Integer')
    end
    unless (0..255).include?(arg)
      malformed(arg_name, '!(0..255)')
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_time(arg_name, arg)
    unless arg.is_a?(Array)
      malformed(arg_name, '!Array')
    end
    unless arg.size == 6
      malformed(arg_name, "size==#{arg.size} -> !6")
    end
    arg.each_with_index do |n,index|
      unless n.is_a?(Integer)
        malformed(arg_name, "[#{index}] -> !Integer")
      end
    end
    well_formed_mktime(arg_name, arg)
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_mktime(arg_name, arg)
    Time.mktime(*arg)
    arg
  rescue => error
    malformed(arg_name, error.message)
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_colour(arg_name, arg)
    unless arg.is_a?(String)
      malformed(arg_name, '!String')
    end
    unless ['red','amber','green','timed_out'].include?(arg)
      malformed(arg_name, "!['red'|'amber'|'green'|'timed_out']")
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_array_of_strings(arg_name, arg)
    unless arg.is_a?(Array)
      malformed(arg_name, '!Array')
    end
    arg.each_with_index do |value,index|
      unless value.is_a?(String)
        malformed(arg_name, "[#{index}] -> !String")
      end
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def well_formed_string(arg_name, arg)
    unless arg.is_a?(String)
      malformed(arg_name, '!String')
    end
    arg
  end

  # - - - - - - - - - - - - - - - -

  def malformed(arg_name, msg)
    raise ClientError.new("malformed:#{arg_name}:#{msg}:")
  end

end
