name: Main Staging (Work in Progress)

on:
  workflow_dispatch:

#on:
#  push:
#    branches:
#      - main

jobs:
  build-test-push:
    uses: cyber-dojo/saver/.github/workflows/main.yml@main
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      KOSLI_HOST: https://staging.app.kosli.com
